Bug #5106: Reverted init.d bash script

diff --git a/base/univention-base-files/conffiles/etc/init.d/networking b/base/univention-base-files/conffiles/etc/init.d/networking
--- a/base/univention-base-files/conffiles/etc/init.d/networking
+++ b/base/univention-base-files/conffiles/etc/init.d/networking
@@ -46,14 +46,14 @@ process_options() {
 check_ifstate() {
     if [ ! -d "$RUN_DIR" ] ; then
 	if ! mkdir -p "$RUN_DIR" ; then
-		log_failure_msg "can't create $RUN_DIR"
-		exit 1
+	    log_failure_msg "can't create $RUN_DIR"
+	    exit 1
 	fi
     fi
     if [ ! -r "$IFSTATE" ] ; then
 	if ! :> "$IFSTATE" ; then
-		log_failure_msg "can't initialise $IFSTATE"
-		exit 1
+	    log_failure_msg "can't initialise $IFSTATE"
+	    exit 1
 	fi
     fi
 }
@@ -69,15 +69,15 @@ check_network_file_systems() {
     while read DEV MTPT FSTYPE REST; do
 	case $DEV in
 	/dev/nbd*|/dev/nd[a-z]*|/dev/etherd/e*)
-		log_warning_msg "not deconfiguring network interfaces: network devices still mounted."
-		exit 0
-		;;
+	    log_warning_msg "not deconfiguring network interfaces: network devices still mounted."
+	    exit 0
+	    ;;
 	esac
 	case $FSTYPE in
 	nfs|nfs4|smbfs|ncp|ncpfs|cifs|coda|ocfs2|gfs|pvfs|pvfs2|fuse.httpfs|fuse.curlftpfs)
-		log_warning_msg "not deconfiguring network interfaces: network file systems still mounted."
-		exit 0
-		;;
+	    log_warning_msg "not deconfiguring network interfaces: network file systems still mounted."
+	    exit 0
+	    ;;
 	esac
     done < /proc/mounts
 }
@@ -88,9 +88,9 @@ check_network_swap() {
     while read DEV MTPT FSTYPE REST; do
 	case $DEV in
 	/dev/nbd*|/dev/nd[a-z]*|/dev/etherd/e*)
-		log_warning_msg "not deconfiguring network interfaces: network swap still mounted."
-		exit 0
-		;;
+	    log_warning_msg "not deconfiguring network interfaces: network swap still mounted."
+	    exit 0
+	    ;;
 	esac
     done < /proc/swaps
 }
@@ -98,19 +98,19 @@ check_network_swap() {
 ifup_hotplug () {
     if [ -d /sys/class/net ]
     then
-		ifaces=$(for iface in $(ifquery --list --allow=hotplug)
-				do
-					link=${iface##:*}
-					link=${link##.*}
-					if [ -e "/sys/class/net/$link" ] && [ "$(cat /sys/class/net/$link/operstate)" = up ]
-					then
-						echo "$iface"
-					fi
-				done)
-		if [ -n "$ifaces" ]
-		then
+	    ifaces=$(for iface in $(ifquery --list --allow=hotplug)
+			    do
+				    link=${iface##:*}
+				    link=${link##.*}
+				    if [ -e "/sys/class/net/$link" ] && [ "$(cat /sys/class/net/$link/operstate)" = up ]
+				    then
+					    echo "$iface"
+				    fi
+			    done)
+	    if [ -n "$ifaces" ]
+	    then
 		ifup $ifaces "$@" || true
-		fi
+	    fi
     fi
 }
 
@@ -137,17 +137,17 @@ start)
 
 	if [ "$CONFIGURE_INTERFACES" = no ]
 	then
-		log_action_msg "Not configuring network interfaces, see /etc/default/networking"
-		exit 0
+	    log_action_msg "Not configuring network interfaces, see /etc/default/networking"
+	    exit 0
 	fi
 	set -f
 	exclusions=$(process_exclusions)
 	log_action_begin_msg "Configuring network interfaces"
 	if ifup -a $exclusions $verbose && ifup_hotplug $exclusions $verbose
 	then
-		log_action_end_msg $?
+	    log_action_end_msg $?
 	else
-		log_action_end_msg $?
+	    log_action_end_msg $?
 	fi
 	;;
 
@@ -160,9 +160,9 @@ stop)
 
 	log_action_begin_msg "Deconfiguring network interfaces"
 	if ifdown -a --exclude=lo $verbose; then
-		log_action_end_msg $?
+	    log_action_end_msg $?
 	else
-		log_action_end_msg $?
+	    log_action_end_msg $?
 	fi
 	;;
 
@@ -173,9 +173,9 @@ reload)
 	state=$(cat /run/network/ifstate)
 	ifdown -a --exclude=lo $verbose || true
 	if ifup --exclude=lo $state $verbose ; then
-		log_action_end_msg $?
+	    log_action_end_msg $?
 	else
-		log_action_end_msg $?
+	    log_action_end_msg $?
 	fi
 	;;
 
@@ -193,9 +193,9 @@ force-reload|restart)
 	exclusions=$(process_exclusions)
 	if ifup -a --exclude=lo $exclusions $verbose && ifup_hotplug $exclusions $verbose
 	then
-		log_action_end_msg $?
+	    log_action_end_msg $?
 	else
-		log_action_end_msg $?
+	    log_action_end_msg $?
 	fi
 	;;
 
